export const menuItems = [
  { id: 'perfil', label: 'Mi Perfil', icon: 'fa-user-shield' },
  { id: 'alumnos', label: 'Estudiantes', icon: 'fa-users' },
  { id: 'docentes', label: 'Docentes', icon: 'fa-chalkboard-teacher' },
  { id: 'preceptores', label: 'Preceptores', icon: 'fa-user-tie' },
  { id: 'administradores', label: 'Administradores', icon: 'fa-user-shield', directorOnly: true },
  { id: 'cursos', label: 'Cursos', icon: 'fa-school' },
  { id: 'materias', label: 'Materias', icon: 'fa-book' },
  { id: 'comunicados', label: 'Comunicados', icon: 'fa-bullhorn' },
  { id: 'notificaciones', label: 'Notificaciones', icon: 'fa-bell' },
  { id: 'horarios', label: 'Horarios', icon: 'fa-clock' },
  { id: 'adelantos-horas', label: 'Adelantos de Horas', icon: 'fa-forward' },
  { id: 'calendario', label: 'Calendario Institucional', icon: 'fa-calendar-alt' },
  { id: 'actas', label: 'Actas', icon: 'fa-file-signature' },
  { id: 'historial', label: 'Historial de Cambios', icon: 'fa-history', roles: ['admin', 'director'] },
  { id: 'suplencias', label: 'Suplencias Docentes', icon: 'fa-user-clock', roles: ['admin', 'director'] },
  { id: 'info', label: 'Información General', icon: 'fa-info-circle' },
];