# Generated by Django 6.0.5 on 2026-05-29 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acta',
            fields=[
                ('id_acta', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'actas',
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('procedencia', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'alumnos',
            },
        ),
        migrations.CreateModel(
            name='CicloLectivo',
            fields=[
                ('id_ciclo', models.AutoField(primary_key=True, serialize=False)),
                ('anio', models.IntegerField()),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ciclos_lectivos',
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id_docente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('correo', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'docentes',
            },
        ),
        migrations.CreateModel(
            name='EstadoAsistencia',
            fields=[
                ('id_estado_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'estados_asistencia',
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id_materia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_materia', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'materias',
            },
        ),
        migrations.CreateModel(
            name='PadreTutor',
            fields=[
                ('id_tutor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'padres_tutores',
            },
        ),
        migrations.CreateModel(
            name='PeriodoEvaluacion',
            fields=[
                ('id_periodo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_periodo', models.CharField(blank=True, max_length=100, null=True)),
                ('orden_periodo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'periodos_evaluacion',
            },
        ),
        migrations.CreateModel(
            name='Preceptor',
            fields=[
                ('id_preceptor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('correo', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'preceptores',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='TipoAccion',
            fields=[
                ('id_tipo_accion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_accion', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tipos_accion',
            },
        ),
        migrations.CreateModel(
            name='TipoActa',
            fields=[
                ('id_tipo_acta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tipos_acta',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=50, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=True)),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='ActaAlumno',
            fields=[
                ('id_acta_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('id_acta', models.ForeignKey(db_column='id_acta', on_delete=django.db.models.deletion.CASCADE, to='gestion_escolar.acta')),
                ('id_alumno', models.ForeignKey(db_column='id_alumno', on_delete=django.db.models.deletion.CASCADE, to='gestion_escolar.alumno')),
            ],
            options={
                'db_table': 'acta_alumno',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_curso', models.CharField(max_length=50)),
                ('turno', models.CharField(blank=True, max_length=50, null=True)),
                ('id_ciclo', models.ForeignKey(blank=True, db_column='id_ciclo', null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_escolar.ciclolectivo')),
                ('id_preceptor', models.ForeignKey(blank=True, db_column='id_preceptor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_escolar.preceptor')),
            ],
            options={
                'db_table': 'cursos',
            },
        ),
        migrations.AddField(
            model_name='alumno',
            name='id_curso',
            field=models.ForeignKey(blank=True, db_column='id_curso', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_escolar.curso'),
        ),
        migrations.CreateModel(
            name='ActaCurso',
            fields=[
                ('id_acta_curso', models.AutoField(primary_key=True, serialize=False)),
                ('id_acta', models.ForeignKey(db_column='id_acta', on_delete=django.db.models.deletion.CASCADE, to='gestion_escolar.acta')),
                ('id_curso', models.ForeignKey(db_column='id_curso', on_delete=django.db.models.deletion.CASCADE, to='gestion_escolar.curso')),
            ],
            options={
                'db_table': 'acta_curso',
            },
        ),
        migrations.CreateModel(
            name='CursoMateria',
            fields=[
                ('id_curso_materia', models.AutoField(primary_key=True, serialize=False)),
                ('id_curso', models.ForeignKey(db_column='id_curso', on_delete=django.db.models.deletion.CASCADE, to='gestion_escolar.curso')),
                ('id_docente', models.ForeignKey(db_column='id_docente', on_delete=django.db.models.deletion.PROTECT, to='gestion_escolar.docente')),
                ('id_materia', models.ForeignKey(db_column='id_materia', on_delete=django.db.models.deletion.CASCADE, to='gestion_escolar.materia')),
            ],
            options={
                'db_table': 'curso_materia',
            },
        ),
        migrations.CreateModel(
            name='DiagnosticoGrupal',
            fields=[
                ('id_diagnostico_grupal', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('id_curso', models.ForeignKey(db_column='id_curso', on_delete=django.db.models.deletion.CASCADE, to='gestion_escolar.curso')),
                ('id_docente', models.ForeignKey(db_column='id_docente', on_delete=django.db.models.deletion.CASCADE, to='gestion_escolar.docente')),
            ],
            options={
                'db_table': 'diagnosticos_grupales',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('dia_semana', models.CharField(blank=True, max_length=20, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('aula', models.CharField(blank=True, max_length=50, null=True)),
                ('id_curso_materia', models.ForeignKey(db_column='id_curso_materia', on_delete=django.db.models.deletion.CASCADE, to='gestion_escolar.cursomateria')),
            ],
            options={
                'db_table': 'horarios',
            },
        ),
        migrations.CreateModel(
            name='InscripcionMateria',
            fields=[
                ('id_inscripcion', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_inscripcion', models.DateField(blank=True, null=True)),
                ('id_alumno', models.ForeignKey(db_column='id_alumno', on_delete=django.db.models.deletion.CASCADE, to='gestion_escolar.alumno')),
                ('id_curso_materia', models.ForeignKey(db_column='id_curso_materia', on_delete=django.db.models.deletion.CASCADE, to='gestion_escolar.cursomateria')),
            ],
            options={
                'db_table': 'inscripciones_materias',
            },
        ),
        migrations.AddField(
            model_name='alumno',
            name='id_tutor',
            field=models.ForeignKey(blank=True, db_column='id_tutor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_escolar.padretutor'),
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id_calificacion', models.AutoField(primary_key=True, serialize=False)),
                ('pre_nota', models.CharField(blank=True, max_length=10, null=True)),
                ('nota_numerica', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('fecha_carga', models.DateTimeField(blank=True, null=True)),
                ('id_alumno', models.ForeignKey(db_column='id_alumno', on_delete=django.db.models.deletion.CASCADE, to='gestion_escolar.alumno')),
                ('id_curso_materia', models.ForeignKey(db_column='id_curso_materia', on_delete=django.db.models.deletion.CASCADE, to='gestion_escolar.cursomateria')),
                ('id_docente', models.ForeignKey(db_column='id_docente', on_delete=django.db.models.deletion.PROTECT, to='gestion_escolar.docente')),
                ('id_periodo', models.ForeignKey(db_column='id_periodo', on_delete=django.db.models.deletion.PROTECT, to='gestion_escolar.periodoevaluacion')),
            ],
            options={
                'db_table': 'calificaciones',
            },
        ),
        migrations.CreateModel(
            name='Planificacion',
            fields=[
                ('id_planificacion', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('ruta_archivo', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_subida', models.DateTimeField(blank=True, null=True)),
                ('id_curso_materia', models.ForeignKey(db_column='id_curso_materia', on_delete=django.db.models.deletion.CASCADE, to='gestion_escolar.cursomateria')),
                ('id_docente', models.ForeignKey(db_column='id_docente', on_delete=django.db.models.deletion.CASCADE, to='gestion_escolar.docente')),
            ],
            options={
                'db_table': 'planificaciones',
            },
        ),
        migrations.AddField(
            model_name='acta',
            name='id_tipo_acta',
            field=models.ForeignKey(db_column='id_tipo_acta', on_delete=django.db.models.deletion.PROTECT, to='gestion_escolar.tipoacta'),
        ),
        migrations.AddField(
            model_name='preceptor',
            name='id_usuario',
            field=models.OneToOneField(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_escolar.usuario'),
        ),
        migrations.AddField(
            model_name='padretutor',
            name='id_usuario',
            field=models.OneToOneField(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_escolar.usuario'),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('leida', models.BooleanField(default=False)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='gestion_escolar.usuario')),
            ],
            options={
                'db_table': 'notificaciones',
            },
        ),
        migrations.CreateModel(
            name='HistorialCambio',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('tabla_modificada', models.CharField(blank=True, max_length=100, null=True)),
                ('id_registro', models.IntegerField(blank=True, null=True)),
                ('valor_anterior', models.TextField(blank=True, null=True)),
                ('valor_nuevo', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('id_tipo_accion', models.ForeignKey(db_column='id_tipo_accion', on_delete=django.db.models.deletion.PROTECT, to='gestion_escolar.tipoaccion')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, to='gestion_escolar.usuario')),
            ],
            options={
                'db_table': 'historial_cambios',
            },
        ),
        migrations.AddField(
            model_name='docente',
            name='id_usuario',
            field=models.OneToOneField(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_escolar.usuario'),
        ),
        migrations.CreateModel(
            name='Directivo',
            fields=[
                ('id_directivo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('id_usuario', models.OneToOneField(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_escolar.usuario')),
            ],
            options={
                'db_table': 'directivos',
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('observacion', models.TextField(blank=True, null=True)),
                ('id_alumno', models.ForeignKey(db_column='id_alumno', on_delete=django.db.models.deletion.CASCADE, to='gestion_escolar.alumno')),
                ('id_curso_materia', models.ForeignKey(db_column='id_curso_materia', on_delete=django.db.models.deletion.CASCADE, to='gestion_escolar.cursomateria')),
                ('id_estado_asistencia', models.ForeignKey(db_column='id_estado_asistencia', on_delete=django.db.models.deletion.PROTECT, to='gestion_escolar.estadoasistencia')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, to='gestion_escolar.usuario')),
            ],
            options={
                'db_table': 'asistencias',
            },
        ),
        migrations.AddField(
            model_name='alumno',
            name='id_usuario',
            field=models.OneToOneField(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_escolar.usuario'),
        ),
        migrations.AddField(
            model_name='acta',
            name='id_usuario_creador',
            field=models.ForeignKey(db_column='id_usuario_creador', on_delete=django.db.models.deletion.PROTECT, to='gestion_escolar.usuario'),
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.CASCADE, to='gestion_escolar.rol')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='gestion_escolar.usuario')),
            ],
            options={
                'db_table': 'usuario_roles',
                'unique_together': {('id_usuario', 'id_rol')},
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='roles',
            field=models.ManyToManyField(related_name='usuarios', through='gestion_escolar.UsuarioRol', to='gestion_escolar.rol'),
        ),
    ]
