export const menuItems = [
  { id: 'perfil', label: 'Mi Perfil', icon: 'fa-user-tie' },
  { id: 'alumnos', label: 'Estudiantes', icon: 'fa-users' },
  { id: 'docentes', label: 'Docentes', icon: 'fa-chalkboard-teacher' },
  { id: 'tutores', label: 'Tutores', icon: 'fa-user-shield' },
  { id: 'asistencias', label: 'Asistencias', icon: 'fa-calendar-check' },
  { id: 'adelantos-horas', label: 'Adelantos de Horas', icon: 'fa-forward' },
  { id: 'actas', label: 'Actas', icon: 'fa-file-alt' },
  { id: 'notas', label: 'Boletines', icon: 'fa-clipboard-list' },
  { id: 'comunicados', label: 'Comunicados', icon: 'fa-bullhorn' },
  { id: 'admin-preceptores', label: 'Administración de Preceptores', icon: 'fa-cogs' },
  { id: 'estadisticas', label: 'Estadísticas', icon: 'fa-chart-bar' },
  { id: 'calendario', label: 'Calendario Institucional', icon: 'fa-calendar-alt' },
  { id: 'notificaciones', label: 'Notificaciones', icon: 'fa-bell' },
];