# Generated by Django 6.0.5 on 2026-06-02 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escuela', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnocurso',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='usuarios.alumno'),
        ),
        migrations.AddField(
            model_name='alumnomateria',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='usuarios.alumno'),
        ),
        migrations.AddField(
            model_name='alumnomateria',
            name='ciclo_lectivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuela.ciclolectivo'),
        ),
        migrations.AddField(
            model_name='alumnocurso',
            name='ciclo_lectivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuela.ciclolectivo'),
        ),
        migrations.AddField(
            model_name='alumnocurso',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='escuela.curso'),
        ),
        migrations.AddField(
            model_name='docentemateria',
            name='ciclo_lectivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuela.ciclolectivo'),
        ),
        migrations.AddField(
            model_name='docentemateria',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='usuarios.docente'),
        ),
        migrations.AddField(
            model_name='materiacurso',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='escuela.curso'),
        ),
        migrations.AddField(
            model_name='materiacurso',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='escuela.materia'),
        ),
        migrations.AddField(
            model_name='docentemateria',
            name='materia_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docentes', to='escuela.materiacurso'),
        ),
        migrations.AddField(
            model_name='alumnomateria',
            name='materia_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='escuela.materiacurso'),
        ),
        migrations.AddField(
            model_name='nota',
            name='alumno_materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='escuela.alumnomateria'),
        ),
        migrations.AddField(
            model_name='nota',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='curso',
            name='orientacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos', to='escuela.orientacion'),
        ),
        migrations.AddField(
            model_name='preceptorcurso',
            name='ciclo_lectivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuela.ciclolectivo'),
        ),
        migrations.AddField(
            model_name='preceptorcurso',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escuela.curso'),
        ),
        migrations.AddField(
            model_name='preceptorcurso',
            name='preceptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_asignados', to='usuarios.empleado'),
        ),
        migrations.AddField(
            model_name='tutoralumno',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutores', to='usuarios.alumno'),
        ),
        migrations.AddField(
            model_name='tutoralumno',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='usuarios.tutor'),
        ),
        migrations.AlterUniqueTogether(
            name='alumnocurso',
            unique_together={('alumno', 'curso', 'ciclo_lectivo')},
        ),
        migrations.AlterUniqueTogether(
            name='materiacurso',
            unique_together={('materia', 'curso')},
        ),
        migrations.AlterUniqueTogether(
            name='docentemateria',
            unique_together={('docente', 'materia_curso', 'ciclo_lectivo')},
        ),
        migrations.AlterUniqueTogether(
            name='alumnomateria',
            unique_together={('alumno', 'materia_curso', 'ciclo_lectivo')},
        ),
        migrations.AlterUniqueTogether(
            name='nota',
            unique_together={('alumno_materia', 'instancia')},
        ),
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together={('anio', 'division', 'orientacion')},
        ),
        migrations.AlterUniqueTogether(
            name='preceptorcurso',
            unique_together={('preceptor', 'curso', 'ciclo_lectivo')},
        ),
        migrations.AlterUniqueTogether(
            name='tutoralumno',
            unique_together={('tutor', 'alumno')},
        ),
    ]
