# Generated by Django 6.0.5 on 2026-06-02 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='anio',
            field=models.IntegerField(default='2026'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='curso',
            name='division',
            field=models.CharField(default=2026, max_length=50),
            preserve_default=False,
        ),
    ]
