# Generated by Django 6.0.5 on 2026-05-22 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActaCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=10)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('curso', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=10)),
                ('fecha', models.DateField()),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ActaAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('materia', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('cargado_por', models.CharField(max_length=150)),
                ('archivo', models.CharField(blank=True, max_length=255)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actas', to='gestion.alumno')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='NotaPreceptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('alumno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nota_preceptor', to='gestion.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('docente', 'Docente'), ('preceptor', 'Preceptor'), ('familia', 'Familia')], max_length=20)),
                ('dni', models.CharField(blank=True, max_length=20)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('apellido', models.CharField(blank=True, max_length=100)),
                ('materia_principal', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SesionClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=10)),
                ('materia', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('libro_temas', models.CharField(blank=True, max_length=500)),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones_dictadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('curso', 'materia', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='AsistenciaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('Presente', 'Presente'), ('Ausente', 'Ausente'), ('Tarde', 'Tarde')], default='Presente', max_length=10)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_diarias', to='gestion.alumno')),
            ],
            options={
                'unique_together': {('alumno', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(max_length=100)),
                ('prenota1', models.CharField(blank=True, max_length=3)),
                ('nota1', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('prenota2', models.CharField(blank=True, max_length=3)),
                ('nota2', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('diagnostico', models.CharField(blank=True, max_length=255)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='gestion.alumno')),
            ],
            options={
                'unique_together': {('alumno', 'materia')},
            },
        ),
        migrations.CreateModel(
            name='AsistenciaClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Presente', 'Presente'), ('Ausente', 'Ausente'), ('Tarde', 'Tarde')], default='Presente', max_length=10)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.alumno')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='gestion.sesionclase')),
            ],
            options={
                'unique_together': {('sesion', 'alumno')},
            },
        ),
        migrations.CreateModel(
            name='VinculoFamilia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vinculo', models.CharField(default='Padre/Madre/Tutor', max_length=50)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familias', to='gestion.alumno')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hijos_vinculados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'alumno')},
            },
        ),
    ]
