from django.contrib import admin

from escuela.models import (
    Acta,
    ActaAlumno,
    ActaCurso,
    Alumno,
    Asistencia,
    Calificacion,
    CicloLectivo,
    Curso,
    CursoMateria,
    DiagnosticoGrupal,
    Directivo,
    Docente,
    EstadoAsistencia,
    Horario,
    InscripcionMateria,
    Materia,
    Notificacion,
    PadreTutor,
    PeriodoEvaluacion,
    Planificacion,
    Preceptor,
    Rol,
    TipoActa,
    Usuario,
)

admin.site.register(Usuario)
admin.site.register(Rol)
admin.site.register(Alumno)
admin.site.register(Docente)
admin.site.register(Preceptor)
admin.site.register(Directivo)
admin.site.register(PadreTutor)
admin.site.register(CicloLectivo)
admin.site.register(Curso)
admin.site.register(Materia)
admin.site.register(CursoMateria)
admin.site.register(Horario)
admin.site.register(InscripcionMateria)
admin.site.register(PeriodoEvaluacion)
admin.site.register(Calificacion)
admin.site.register(EstadoAsistencia)
admin.site.register(Asistencia)
admin.site.register(TipoActa)
admin.site.register(Acta)
admin.site.register(ActaAlumno)
admin.site.register(ActaCurso)
admin.site.register(Planificacion)
admin.site.register(DiagnosticoGrupal)
admin.site.register(Notificacion)
